# Generated by Django 5.2.1 on 2025-06-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(default=None, related_name='participating_trips', through='KJObackend.Participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'In Progress'), (2, 'Done')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='KJObackend.participant')),
                ('trip', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='KJObackend.trip')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participants', to='KJObackend.trip'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='KJObackend.participant')),
                ('shared_between', models.ManyToManyField(related_name='shared_expenses', to='KJObackend.participant')),
                ('trip', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='KJObackend.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('trip', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='KJObackend.trip')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'trip')},
        ),
    ]
